export const CHARACTER_CODE_A = 65;
export const ROWS = 12;
export const COLS = 9;
export const MAX_PLAYERS = 6;
export const INITIAL_PLAYER_MONEY = 3000;
export const MINIMUM_PLAYERS = 2;
export const TILES_PER_HAND = 6;
export const RESERVED_NAMES = ['bank', 'bag', 'board', 'dead'];
export const SAFE_HOTEL_SIZE = 11;
