// error-codes.ts
export const GameErrorCodes = {
  // Add player errors
  NOT_ADDING_PLAYERS: "NOT_ADDING_PLAYERS",
  PLAYERS_MAX: "PLAYERS_MAX",
  INVALID_PLAYER_NAME: "INVALID_PLAYER_NAME",
  PLAYER_EXISTS: "PLAYER_EXISTS",

  // game errors
  NOT_ENOUGH_PLAYERS: "NOT_ENOUGH_PLAYERS",
  INVALID_ACTION: "INVALID_ACTION",
  
  // Resource errors
  INSUFFICIENT_RESOURCES: "INSUFFICIENT_RESOURCES",

  // Placement errors
  INVALID_LOCATION: "INVALID_LOCATION",
  LOCATION_OCCUPIED: "LOCATION_OCCUPIED",
  DISTANCE_RULE_VIOLATION: "DISTANCE_RULE_VIOLATION",

  // Trade errors
  INVALID_TRADE_OFFER: "INVALID_TRADE_OFFER",

  // System errors
  VERSION_CONFLICT: "VERSION_CONFLICT",
  PROCESSING_ERROR: "PROCESSING_ERROR",
};
